#!/bin/bash 

#####################################
#  Riadh Hamdi <rhamdi@redhat.com>  #
#                                   #
#                                   #
#####################################


if [ $# -eq 0 ]
then
echo "***Invalid Number of arguments***"
echo "   Usage:      --establish-root
                     --generate-csr
                    --sign-csr        " 
exit 0
fi

if [ $1 == "--establish-root" ]

then

echo "Establishing new RootCA and KeyFile...."
echo 
echo 
sleep 1
echo "Please answer the following questions"
echo 
echo
echo "Choose the working directory of the rootCA and the keyfile"
read WORKING_DIR
#Creating the working directory if doesnt exist 
test -d $WORKING_DIR || mkdir -p $WORKING_DIR && echo "working directory created"
echo
echo 
echo "Creating the Key..."
sleep 1
echo 
openssl genrsa -des3 -out $WORKING_DIR/rootCA.key 4096
echo 
openssl req -x509 -new -nodes -key $WORKING_DIR/rootCA.key -sha256 -days 1024 -out $WORKING_DIR/rootCA.crt
echo 
exit 0
fi
if [ $1 == "--generate-csr" ]
then
CSRNAME=$(hostname -s)
echo $CSRNAME

echo "Choose your working directory... All the files will be stored there"
read WORKING_DIR
echo "You will be promted to reinter the passphrase twice"
echo
test -d $WORKING_DIR || mkdir -p $WORKING_DIR && echo "working directory created"
openssl genrsa -des3 -out $WORKING_DIR/$CSRNAME.pem 1024
openssl rsa -in $WORKING_DIR/$CSRNAME.pem -out $WORKING_DIR/$CSRNAME.key
echo 
echo
openssl req -new -key $WORKING_DIR/$CSRNAME.key -out $WORKING_DIR/$CSRNAME.csr 

echo 
echo "You generated Key is stored in: $WORKING_DIR/$CSRNAME.key"
echo 
echo "You generated CSR is stored in: $WORKING_DIR/$CSRNAME.csr"
exit 0
fi 

if [ $1 == "--sign-csr" ]
then
echo "Provide the Full path to your ROOTCA certfile"
echo 
read CAPATH
echo "Provide the Full path to your ROOTCA keyfile"
echo
read CAKEYPATH
echo 
echo "Provide the Full path to your CSR certfile"
echo
read CSRPATH
echo 
echo Signing CSR
openssl x509 -req -days 360 -in $CSRPATH -CA $CAPATH -CAkey $CAKEYPATH -CAcreateserial -out /tmp/generated.crt -sha256
echo "your signed certificate is stored in /tmp/generated.crt"
echo 
exit 0
fi 

